#!/usr/bin/env python3
"""
Setup script for encryption key configuration

This script helps generate and configure a consistent encryption key
for the AI News Aggregator backend. The encryption key is used for:
1. Encrypting API keys in the Settings table
2. Session token generation (consistency)

Running this script will:
1. Generate a new encryption key if one doesn't exist
2. Create/update .env file with the key
3. Provide instructions for consistent usage

Usage:
    python3 setup_encryption.py
"""

from cryptography.fernet import Fernet
import os
from pathlib import Path


def generate_encryption_key():
    """Generate a new Fernet encryption key"""
    return Fernet.generate_key().decode()


def read_env_file(env_path):
    """Read existing .env file and return as dict"""
    env_vars = {}
    if env_path.exists():
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip()
    return env_vars


def write_env_file(env_path, env_vars):
    """Write env vars to .env file"""
    with open(env_path, "w") as f:
        f.write("# AI News Aggregator - Backend Configuration\n")
        f.write("# Generated by setup_encryption.py\n\n")

        f.write("# Database Configuration\n")
        f.write(f"DATABASE_URL={env_vars.get('DATABASE_URL', 'sqlite:///./ai_news.db')}\n\n")

        f.write("# Encryption Key for API keys and sessions\n")
        f.write("# IMPORTANT: Keep this key consistent across restarts!\n")
        f.write("# Changing this key will make existing encrypted API keys unreadable\n")
        f.write(f"ENCRYPTION_KEY={env_vars.get('ENCRYPTION_KEY', '')}\n\n")

        f.write("# Session Configuration\n")
        f.write(f"SESSION_EXPIRE_DAYS={env_vars.get('SESSION_EXPIRE_DAYS', '30')}\n")


def main():
    print("=" * 60)
    print("Encryption Key Setup for AI News Aggregator")
    print("=" * 60)
    print()

    # Get backend directory
    backend_dir = Path(__file__).parent
    env_path = backend_dir / ".env"
    env_example_path = backend_dir / ".env.example"

    print(f"Backend directory: {backend_dir}")
    print(f".env file path: {env_path}")
    print()

    # Read existing .env or create from example
    env_vars = {}

    if env_path.exists():
        print("✓ Found existing .env file")
        env_vars = read_env_file(env_path)

        if "ENCRYPTION_KEY" in env_vars and env_vars["ENCRYPTION_KEY"]:
            print(f"✓ Encryption key already configured")
            print(f"  Current key: {env_vars['ENCRYPTION_KEY'][:20]}...")
            print()

            response = input("Do you want to generate a NEW encryption key? (yes/no): ").lower()

            if response in ["yes", "y"]:
                print("\n⚠️  WARNING: Generating a new key will make existing encrypted")
                print("   API keys in the database UNREADABLE!")
                print()
                confirm = input("Are you SURE you want to continue? (yes/no): ").lower()

                if confirm in ["yes", "y"]:
                    new_key = generate_encryption_key()
                    env_vars["ENCRYPTION_KEY"] = new_key
                    print("\n✓ New encryption key generated")
                else:
                    print("\n✓ Keeping existing encryption key")
            else:
                print("\n✓ Keeping existing encryption key")
        else:
            print("⚠️  No encryption key found in .env file")
            new_key = generate_encryption_key()
            env_vars["ENCRYPTION_KEY"] = new_key
            print("✓ Generated new encryption key")
    else:
        print("No .env file found - creating new one")

        # Start with defaults
        env_vars = {"DATABASE_URL": "sqlite:///./ai_news.db", "SESSION_EXPIRE_DAYS": "30"}

        # Generate new key
        new_key = generate_encryption_key()
        env_vars["ENCRYPTION_KEY"] = new_key
        print("✓ Generated new encryption key")

    # Ensure all required vars are present
    if "DATABASE_URL" not in env_vars:
        env_vars["DATABASE_URL"] = "sqlite:///./ai_news.db"

    if "SESSION_EXPIRE_DAYS" not in env_vars:
        env_vars["SESSION_EXPIRE_DAYS"] = "30"

    # Write .env file
    write_env_file(env_path, env_vars)
    print(f"\n✓ Configuration written to: {env_path}")

    # Display summary
    print("\n" + "=" * 60)
    print("Configuration Summary")
    print("=" * 60)
    print(f"DATABASE_URL: {env_vars['DATABASE_URL']}")
    print(
        f"ENCRYPTION_KEY: {env_vars['ENCRYPTION_KEY'][:20]}... ({len(env_vars['ENCRYPTION_KEY'])} chars)"
    )
    print(f"SESSION_EXPIRE_DAYS: {env_vars['SESSION_EXPIRE_DAYS']}")
    print()

    # Important notes
    print("=" * 60)
    print("IMPORTANT NOTES")
    print("=" * 60)
    print()
    print("1. ENCRYPTION KEY CONSISTENCY:")
    print("   - The encryption key must stay the same across server restarts")
    print("   - Changing it will make existing encrypted API keys unreadable")
    print("   - Keep this .env file safe and backed up")
    print()
    print("2. SECURITY:")
    print("   - Never commit .env file to version control")
    print("   - .env is already in .gitignore")
    print("   - Keep the encryption key secret")
    print()
    print("3. BACKUP:")
    print("   - Consider backing up your .env file securely")
    print("   - Store it separately from the codebase")
    print("   - Use a password manager or secrets vault")
    print()
    print("4. PRODUCTION:")
    print("   - Use environment variables instead of .env file")
    print("   - Store secrets in secure vaults (AWS Secrets Manager, etc.)")
    print("   - Never expose the encryption key in logs or error messages")
    print()

    # Next steps
    print("=" * 60)
    print("Next Steps")
    print("=" * 60)
    print()
    print("1. Start the backend server:")
    print("   python3 main.py")
    print()
    print("2. Configure your API keys via the Settings API:")
    print("   POST http://localhost:8001/api/settings")
    print("   {")
    print('     "key": "openai_api_key",')
    print('     "value": "sk-...",')
    print('     "encrypted": true')
    print("   }")
    print()
    print("3. The encryption key will be used automatically")
    print()
    print("4. Your API keys are now safely encrypted in the database")
    print()
    print("=" * 60)
    print("Setup Complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
